### ISSUE TITLE
Potential incorrect residual

### ISSUE THREAD

**Issue by VHellendoorn** [lucidrains/Mega-pytorch#2]
Hi, thanks for providing this implementation! I'm looking into transcribing it for use in the NeoX toolkit and following it line-by-line. One potential issue that doesn't affect me, but might for others is that this line:

https://github.com/lucidrains/Mega-pytorch/blob/fd70791dd5e0b4dcc4895d621200d112ca320622/mega_pytorch/mega_pytorch.py#L305

should be using `residual` instead of `x` on the far right end. As is, the `residual` variable is unused.

**Comment by lucidrains** [comment]
@VHellendoorn thank you Vincent! https://github.com/lucidrains/Mega-pytorch/commit/188da8bbd50e6a44bb4e10e13b32e8bbd628de4e
